In [57]:
import pandas as pd
import numpy as np

In [58]:
#df=pd.read_csv("data/raw/food_access_file/Food%20Access%20Research%20Atlas.csv")

df=pd.read_csv("../data/raw/food_access_file/Food_Access_Research_Atlas.csv")

In [59]:
df.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,1001020100,Alabama,Autauga County,1,1912,693,0,0.0,0.00,0,...,221.0,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0,102.0
1,1001020200,Alabama,Autauga County,1,2170,743,0,181.0,8.34,1,...,214.0,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0,156.0
2,1001020300,Alabama,Autauga County,1,3373,1256,0,0.0,0.00,0,...,439.0,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0,172.0
3,1001020400,Alabama,Autauga County,1,4386,1722,0,0.0,0.00,0,...,904.0,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0,98.0
4,1001020500,Alabama,Autauga County,1,10766,4082,0,181.0,1.68,0,...,1126.0,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0,339.0

In [60]:
#Limiting DF to Cook County, Illinois (Chicago Metro Area)
df_cook=df[(df['State']=="Illinois")&(df["County"]=="Cook County")].copy()

In [61]:
df_cook.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1314 entries, 20935 to 22248
Columns: 147 entries, CensusTract to TractSNAP
dtypes: float64(126), int64(19), object(2)
memory usage: 1.5+ MB

In [62]:
df_cook.describe()

,CensusTract,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,LILATracts_halfAnd10,LILATracts_1And20,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
count,1.314000e+03,1314.000000,1314.000000,1314.000000,1314.000000,1314.000000,1314.000000,1314.000000,1314.000000,1314.000000,...,1314.000000,1314.000000,1314.000000,1314.000000,1314.000000,1314.000000,1314.000000,1314.000000,1314.000000,1314.000000
mean,1.703156e+10,0.998478,3953.329528,1496.465753,0.003805,68.707763,1.738508,0.038813,0.251903,0.038813,...,472.092085,2189.659056,980.035769,245.564688,1.312024,16.407154,520.350837,947.307458,264.414003,225.845510
std,2.944146e+05,0.038999,1788.800486,761.006299,0.061592,352.577133,6.321919,0.193222,0.434271,0.193222,...,325.879117,1720.728622,1360.831217,429.268700,2.516975,18.437337,663.108800,1265.664299,310.392061,191.581993
min,1.703101e+10,0.000000,237.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,11.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,1.703125e+10,1.000000,2548.000000,964.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,227.000000,629.750000,77.000000,15.000000,0.000000,4.000000,99.000000,135.000000,91.000000,77.000000
50%,1.703172e+10,1.000000,3848.000000,1424.000000,0.000000,2.000000,0.060000,0.000000,0.000000,0.000000,...,407.500000,2064.500000,263.500000,90.500000,0.000000,10.000000,241.000000,397.500000,174.500000,185.000000
75%,1.703182e+10,1.000000,5149.500000,1893.000000,0.000000,30.750000,0.937500,0.000000,1.000000,0.000000,...,648.750000,3380.750000,1439.500000,276.000000,2.000000,22.000000,673.250000,1181.500000,308.500000,315.000000
max,1.703184e+10,1.000000,16735.000000,9751.000000,1.000000,10273.000000,90.840000,1.000000,1.000000,1.000000,...,2160.000000,9110.000000,7603.000000,6447.000000,38.000000,129.000000,3659.000000,6699.000000,3473.000000,1151.000000

In [63]:
pd.options.display.max_seq_items=200
df_cook.columns

Index(['CensusTract', 'State', 'County', 'Urban', 'Pop2010', 'OHU2010',
       'GroupQuartersFlag', 'NUMGQTRS', 'PCTGQTRS', 'LILATracts_1And10',
       'LILATracts_halfAnd10', 'LILATracts_1And20', 'LILATracts_Vehicle',
       'HUNVFlag', 'LowIncomeTracts', 'PovertyRate', 'MedianFamilyIncome',
       'LA1and10', 'LAhalfand10', 'LA1and20', 'LATracts_half', 'LATracts1',
       'LATracts10', 'LATracts20', 'LATractsVehicle_20', 'LAPOP1_10',
       'LAPOP05_10', 'LAPOP1_20', 'LALOWI1_10', 'LALOWI05_10', 'LALOWI1_20',
       'lapophalf', 'lapophalfshare', 'lalowihalf', 'lalowihalfshare',
       'lakidshalf', 'lakidshalfshare', 'laseniorshalf', 'laseniorshalfshare',
       'lawhitehalf', 'lawhitehalfshare', 'lablackhalf', 'lablackhalfshare',
       'laasianhalf', 'laasianhalfshare', 'lanhopihalf', 'lanhopihalfshare',
       'laaianhalf', 'laaianhalfshare', 'laomultirhalf', 'laomultirhalfshare',
       'lahisphalf', 'lahisphalfshare', 'lahunvhalf', 'lahunvhalfshare',
       'lasnaphalf', 'lasnaphalfshare', 'lapop1', 'lapop1share', 'lalowi1',
       'lalowi1share', 'lakids1', 'lakids1share', 'laseniors1',
       'laseniors1share', 'lawhite1', 'lawhite1share', 'lablack1',
       'lablack1share', 'laasian1', 'laasian1share', 'lanhopi1',
       'lanhopi1share', 'laaian1', 'laaian1share', 'laomultir1',
       'laomultir1share', 'lahisp1', 'lahisp1share', 'lahunv1', 'lahunv1share',
       'lasnap1', 'lasnap1share', 'lapop10', 'lapop10share', 'lalowi10',
       'lalowi10share', 'lakids10', 'lakids10share', 'laseniors10',
       'laseniors10share', 'lawhite10', 'lawhite10share', 'lablack10',
       'lablack10share', 'laasian10', 'laasian10share', 'lanhopi10',
       'lanhopi10share', 'laaian10', 'laaian10share', 'laomultir10',
       'laomultir10share', 'lahisp10', 'lahisp10share', 'lahunv10',
       'lahunv10share', 'lasnap10', 'lasnap10share', 'lapop20', 'lapop20share',
       'lalowi20', 'lalowi20share', 'lakids20', 'lakids20share', 'laseniors20',
       'laseniors20share', 'lawhite20', 'lawhite20share', 'lablack20',
       'lablack20share', 'laasian20', 'laasian20share', 'lanhopi20',
       'lanhopi20share', 'laaian20', 'laaian20share', 'laomultir20',
       'laomultir20share', 'lahisp20', 'lahisp20share', 'lahunv20',
       'lahunv20share', 'lasnap20', 'lasnap20share', 'TractLOWI', 'TractKids',
       'TractSeniors', 'TractWhite', 'TractBlack', 'TractAsian', 'TractNHOPI',
       'TractAIAN', 'TractOMultir', 'TractHispanic', 'TractHUNV', 'TractSNAP'],
      dtype='object')

In [64]:
#Identifying number of missing/NaN values in each column
pd.options.display.max_rows=200
df_cook.isna().sum()

CensusTract                0
State                      0
County                     0
Urban                      0
Pop2010                    0
OHU2010                    0
GroupQuartersFlag          0
NUMGQTRS                   0
PCTGQTRS                   0
LILATracts_1And10          0
LILATracts_halfAnd10       0
LILATracts_1And20          0
LILATracts_Vehicle         0
HUNVFlag                   0
LowIncomeTracts            0
PovertyRate                0
MedianFamilyIncome         9
LA1and10                   0
LAhalfand10                0
LA1and20                   0
LATracts_half              0
LATracts1                  0
LATracts10                 0
LATracts20                 0
LATractsVehicle_20         0
LAPOP1_10                974
LAPOP05_10               381
LAPOP1_20                974
LALOWI1_10               974
LALOWI05_10              381
LALOWI1_20               974
lapophalf                379
lapophalfshare           379
lalowihalf               379
lalowihalfshare          379
lakidshalf               379
lakidshalfshare          379
laseniorshalf            379
laseniorshalfshare       379
lawhitehalf              379
lawhitehalfshare         379
lablackhalf              379
lablackhalfshare         379
laasianhalf              379
laasianhalfshare         379
lanhopihalf              379
lanhopihalfshare         379
laaianhalf               379
laaianhalfshare          379
laomultirhalf            379
laomultirhalfshare       379
lahisphalf               379
lahisphalfshare          379
lahunvhalf               379
lahunvhalfshare          379
lasnaphalf               379
lasnaphalfshare          379
lapop1                   972
lapop1share              972
lalowi1                  972
lalowi1share             972
lakids1                  972
lakids1share             972
laseniors1               972
laseniors1share          972
lawhite1                 972
lawhite1share            972
lablack1                 972
lablack1share            972
laasian1                 972
laasian1share            972
lanhopi1                 972
lanhopi1share            972
laaian1                  972
laaian1share             972
laomultir1               972
laomultir1share          972
lahisp1                  972
lahisp1share             972
lahunv1                  972
lahunv1share             972
lasnap1                  972
lasnap1share             972
lapop10                 1314
lapop10share            1314
lalowi10                1314
lalowi10share           1314
lakids10                1314
lakids10share           1314
laseniors10             1314
laseniors10share        1314
lawhite10               1314
lawhite10share          1314
lablack10               1314
lablack10share          1314
laasian10               1314
laasian10share          1314
lanhopi10               1314
lanhopi10share          1314
laaian10                1314
laaian10share           1314
laomultir10             1314
laomultir10share        1314
lahisp10                1314
lahisp10share           1314
lahunv10                1314
lahunv10share           1314
lasnap10                1314
lasnap10share           1314
lapop20                 1314
lapop20share            1314
lalowi20                1314
lalowi20share           1314
lakids20                1314
lakids20share           1314
laseniors20             1314
laseniors20share        1314
lawhite20               1314
lawhite20share          1314
lablack20               1314
lablack20share          1314
laasian20               1314
laasian20share          1314
lanhopi20               1314
lanhopi20share          1314
laaian20                1314
laaian20share           1314
laomultir20             1314
laomultir20share        1314
lahisp20                1314
lahisp20share           1314
lahunv20                1314
lahunv20share           1314
lasnap20                1314
lasnap20share           1314
TractLOWI                  0
TractKids                  0
TractSeniors               0
TractWhite                 0
TractBlack                 0
TractAsian                 0
TractNHOPI                 0
TractAIAN                  0
TractOMultir               0
TractHispanic              0
TractHUNV                  0
TractSNAP                  0
dtype: int64

In [65]:
len(df_cook)

1314

In [66]:
#Create a list of all columns with no values
blank_columns=[i for i in df_cook.columns if df_cook[i].isna().sum()==1314]

In [67]:
#Drop columns where every value is missing/NaN
df_cook=df_cook.drop(blank_columns,axis=1)

In [68]:
df_cook['LA1and10'].value_counts(dropna=False)

0    1146
1     168
Name: LA1and10, dtype: int64

In [69]:
df_cook.isna().sum()

CensusTract               0
State                     0
County                    0
Urban                     0
Pop2010                   0
OHU2010                   0
GroupQuartersFlag         0
NUMGQTRS                  0
PCTGQTRS                  0
LILATracts_1And10         0
LILATracts_halfAnd10      0
LILATracts_1And20         0
LILATracts_Vehicle        0
HUNVFlag                  0
LowIncomeTracts           0
PovertyRate               0
MedianFamilyIncome        9
LA1and10                  0
LAhalfand10               0
LA1and20                  0
LATracts_half             0
LATracts1                 0
LATracts10                0
LATracts20                0
LATractsVehicle_20        0
LAPOP1_10               974
LAPOP05_10              381
LAPOP1_20               974
LALOWI1_10              974
LALOWI05_10             381
LALOWI1_20              974
lapophalf               379
lapophalfshare          379
lalowihalf              379
lalowihalfshare         379
lakidshalf              379
lakidshalfshare         379
laseniorshalf           379
laseniorshalfshare      379
lawhitehalf             379
lawhitehalfshare        379
lablackhalf             379
lablackhalfshare        379
laasianhalf             379
laasianhalfshare        379
lanhopihalf             379
lanhopihalfshare        379
laaianhalf              379
laaianhalfshare         379
laomultirhalf           379
laomultirhalfshare      379
lahisphalf              379
lahisphalfshare         379
lahunvhalf              379
lahunvhalfshare         379
lasnaphalf              379
lasnaphalfshare         379
lapop1                  972
lapop1share             972
lalowi1                 972
lalowi1share            972
lakids1                 972
lakids1share            972
laseniors1              972
laseniors1share         972
lawhite1                972
lawhite1share           972
lablack1                972
lablack1share           972
laasian1                972
laasian1share           972
lanhopi1                972
lanhopi1share           972
laaian1                 972
laaian1share            972
laomultir1              972
laomultir1share         972
lahisp1                 972
lahisp1share            972
lahunv1                 972
lahunv1share            972
lasnap1                 972
lasnap1share            972
TractLOWI                 0
TractKids                 0
TractSeniors              0
TractWhite                0
TractBlack                0
TractAsian                0
TractNHOPI                0
TractAIAN                 0
TractOMultir              0
TractHispanic             0
TractHUNV                 0
TractSNAP                 0
dtype: int64

In [70]:
df_cook.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1314 entries, 20935 to 22248
Data columns (total 95 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CensusTract           1314 non-null   int64
 1   State                 1314 non-null   object
 2   County                1314 non-null   object
 3   Urban                 1314 non-null   int64
 4   Pop2010               1314 non-null   int64
 5   OHU2010               1314 non-null   int64
 6   GroupQuartersFlag     1314 non-null   int64
 7   NUMGQTRS              1314 non-null   float64
 8   PCTGQTRS              1314 non-null   float64
 9   LILATracts_1And10     1314 non-null   int64
 10  LILATracts_halfAnd10  1314 non-null   int64
 11  LILATracts_1And20     1314 non-null   int64
 12  LILATracts_Vehicle    1314 non-null   int64
 13  HUNVFlag              1314 non-null   int64
 14  LowIncomeTracts       1314 non-null   int64
 15  PovertyRate           1314 non-null   float64
 16  MedianFamilyIncome    1305 non-null   float64
 17  LA1and10              1314 non-null   int64
 18  LAhalfand10           1314 non-null   int64
 19  LA1and20              1314 non-null   int64
 20  LATracts_half         1314 non-null   int64
 21  LATracts1             1314 non-null   int64
 22  LATracts10            1314 non-null   int64
 23  LATracts20            1314 non-null   int64
 24  LATractsVehicle_20    1314 non-null   int64
 25  LAPOP1_10             340 non-null    float64
 26  LAPOP05_10            933 non-null    float64
 27  LAPOP1_20             340 non-null    float64
 28  LALOWI1_10            340 non-null    float64
 29  LALOWI05_10           933 non-null    float64
 30  LALOWI1_20            340 non-null    float64
 31  lapophalf             935 non-null    float64
 32  lapophalfshare        935 non-null    float64
 33  lalowihalf            935 non-null    float64
 34  lalowihalfshare       935 non-null    float64
 35  lakidshalf            935 non-null    float64
 36  lakidshalfshare       935 non-null    float64
 37  laseniorshalf         935 non-null    float64
 38  laseniorshalfshare    935 non-null    float64
 39  lawhitehalf           935 non-null    float64
 40  lawhitehalfshare      935 non-null    float64
 41  lablackhalf           935 non-null    float64
 42  lablackhalfshare      935 non-null    float64
 43  laasianhalf           935 non-null    float64
 44  laasianhalfshare      935 non-null    float64
 45  lanhopihalf           935 non-null    float64
 46  lanhopihalfshare      935 non-null    float64
 47  laaianhalf            935 non-null    float64
 48  laaianhalfshare       935 non-null    float64
 49  laomultirhalf         935 non-null    float64
 50  laomultirhalfshare    935 non-null    float64
 51  lahisphalf            935 non-null    float64
 52  lahisphalfshare       935 non-null    float64
 53  lahunvhalf            935 non-null    float64
 54  lahunvhalfshare       935 non-null    float64
 55  lasnaphalf            935 non-null    float64
 56  lasnaphalfshare       935 non-null    float64
 57  lapop1                342 non-null    float64
 58  lapop1share           342 non-null    float64
 59  lalowi1               342 non-null    float64
 60  lalowi1share          342 non-null    float64
 61  lakids1               342 non-null    float64
 62  lakids1share          342 non-null    float64
 63  laseniors1            342 non-null    float64
 64  laseniors1share       342 non-null    float64
 65  lawhite1              342 non-null    float64
 66  lawhite1share         342 non-null    float64
 67  lablack1              342 non-null    float64
 68  lablack1share         342 non-null    float64
 69  laasian1              342 non-null    float64
 70  laasian1share         342 non-null    float64
 71  lanhopi1              342 non-null    float64
 72  lanhopi1share         342 non-null    float64
 73  laaian1               342 non-null    float64
 74  laaian1share          342 non-null    float64
 75  laomultir1            342 non-null    float64
 76  laomultir1share       342 non-null    float64
 77  lahisp1               342 non-null    float64
 78  lahisp1share          342 non-null    float64
 79  lahunv1               342 non-null    float64
 80  lahunv1share          342 non-null    float64
 81  lasnap1               342 non-null    float64
 82  lasnap1share          342 non-null    float64
 83  TractLOWI             1314 non-null   float64
 84  TractKids             1314 non-null   float64
 85  TractSeniors          1314 non-null   float64
 86  TractWhite            1314 non-null   float64
 87  TractBlack            1314 non-null   float64
 88  TractAsian            1314 non-null   float64
 89  TractNHOPI            1314 non-null   float64
 90  TractAIAN             1314 non-null   float64
 91  TractOMultir          1314 non-null   float64
 92  TractHispanic         1314 non-null   float64
 93  TractHUNV             1314 non-null   float64
 94  TractSNAP             1314 non-null   float64
dtypes: float64(74), int64(19), object(2)
memory usage: 985.5+ KB

In [71]:
df_cook=df_cook.fillna(np.nan)

In [72]:
#Assess whether missing MedianFamilyIncome values are in low income tracts or non-low income tracts

df_cook[df_cook["MedianFamilyIncome"].isna()]['LowIncomeTracts']

21286    1
21335    1
21338    1
21348    1
21349    1
21373    1
21383    1
21559    1
22235    1
Name: LowIncomeTracts, dtype: int64

In [73]:
#Replace missing MedianFamilyIncome values with the average of the medians of low income tracts 

#low_income_mean=df_cook[df_cook["LowIncomeTracts"]==1]['MedianFamilyIncome'].mean()
#df_cook["MedianFamilyIncome"]=df_cook['MedianFamilyIncome'].replace(np.nan,low_income_mean)

#Using median of low income tracts instead of mean, because the distribution is skewed

low_income_median=df_cook[df_cook["LowIncomeTracts"]==1]['MedianFamilyIncome'].median()
df_cook["MedianFamilyIncome"]=df_cook['MedianFamilyIncome'].replace(np.nan,low_income_median)

In [74]:
low_income_median

48432.5

In [75]:
#Dropping columns with only 342 non-null values (which focus on >1 mile access)
df_cook=df_cook.dropna(thresh=935,axis=1)

In [76]:
df_cook.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1314 entries, 20935 to 22248
Data columns (total 63 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CensusTract           1314 non-null   int64
 1   State                 1314 non-null   object
 2   County                1314 non-null   object
 3   Urban                 1314 non-null   int64
 4   Pop2010               1314 non-null   int64
 5   OHU2010               1314 non-null   int64
 6   GroupQuartersFlag     1314 non-null   int64
 7   NUMGQTRS              1314 non-null   float64
 8   PCTGQTRS              1314 non-null   float64
 9   LILATracts_1And10     1314 non-null   int64
 10  LILATracts_halfAnd10  1314 non-null   int64
 11  LILATracts_1And20     1314 non-null   int64
 12  LILATracts_Vehicle    1314 non-null   int64
 13  HUNVFlag              1314 non-null   int64
 14  LowIncomeTracts       1314 non-null   int64
 15  PovertyRate           1314 non-null   float64
 16  MedianFamilyIncome    1314 non-null   float64
 17  LA1and10              1314 non-null   int64
 18  LAhalfand10           1314 non-null   int64
 19  LA1and20              1314 non-null   int64
 20  LATracts_half         1314 non-null   int64
 21  LATracts1             1314 non-null   int64
 22  LATracts10            1314 non-null   int64
 23  LATracts20            1314 non-null   int64
 24  LATractsVehicle_20    1314 non-null   int64
 25  lapophalf             935 non-null    float64
 26  lapophalfshare        935 non-null    float64
 27  lalowihalf            935 non-null    float64
 28  lalowihalfshare       935 non-null    float64
 29  lakidshalf            935 non-null    float64
 30  lakidshalfshare       935 non-null    float64
 31  laseniorshalf         935 non-null    float64
 32  laseniorshalfshare    935 non-null    float64
 33  lawhitehalf           935 non-null    float64
 34  lawhitehalfshare      935 non-null    float64
 35  lablackhalf           935 non-null    float64
 36  lablackhalfshare      935 non-null    float64
 37  laasianhalf           935 non-null    float64
 38  laasianhalfshare      935 non-null    float64
 39  lanhopihalf           935 non-null    float64
 40  lanhopihalfshare      935 non-null    float64
 41  laaianhalf            935 non-null    float64
 42  laaianhalfshare       935 non-null    float64
 43  laomultirhalf         935 non-null    float64
 44  laomultirhalfshare    935 non-null    float64
 45  lahisphalf            935 non-null    float64
 46  lahisphalfshare       935 non-null    float64
 47  lahunvhalf            935 non-null    float64
 48  lahunvhalfshare       935 non-null    float64
 49  lasnaphalf            935 non-null    float64
 50  lasnaphalfshare       935 non-null    float64
 51  TractLOWI             1314 non-null   float64
 52  TractKids             1314 non-null   float64
 53  TractSeniors          1314 non-null   float64
 54  TractWhite            1314 non-null   float64
 55  TractBlack            1314 non-null   float64
 56  TractAsian            1314 non-null   float64
 57  TractNHOPI            1314 non-null   float64
 58  TractAIAN             1314 non-null   float64
 59  TractOMultir          1314 non-null   float64
 60  TractHispanic         1314 non-null   float64
 61  TractHUNV             1314 non-null   float64
 62  TractSNAP             1314 non-null   float64
dtypes: float64(42), int64(19), object(2)
memory usage: 657.0+ KB

In [77]:
#Explore how many census tracts with missing values for lasnaphalfshare are in low income census tracts to see if 
#there may be a link between low income census tracks and missing values 
df_cook[df_cook['lasnaphalfshare'].isna()]['LowIncomeTracts'].value_counts(dropna=False)

1    237
0    142
Name: LowIncomeTracts, dtype: int64

In [78]:
#Explore how many census tracts with missing values for lasnaphalf are in low income census tracts to see if 
#there may be a link between low income census tracks and missing values 
df_cook[df_cook['lasnaphalf'].isna()]['LowIncomeTracts'].value_counts(dropna=False)

1    237
0    142
Name: LowIncomeTracts, dtype: int64

In [79]:
#Verify that all census tracts with missing values for lasnaphalf also have missing values for lasnaphalfshare
(df_cook[df_cook['lasnaphalf'].isna()]['CensusTract'].value_counts(dropna=False)==df_cook[df_cook['lasnaphalfshare'].isna()]['CensusTract'].value_counts(dropna=False)).value_counts()

True    379
Name: CensusTract, dtype: int64

In [80]:
df_cook[df_cook['lasnaphalf'].isna()]['LILATracts_halfAnd10'].value_counts(dropna=False)

0    379
Name: LILATracts_halfAnd10, dtype: int64

In [81]:
#It appears that all missing values for population/share of population variables are NaN if the census tract is not
#tagged as being a census tract with a flag for low access at 0.5 miles for urban areas or 10 miles for rural areas
df_cook[df_cook['LILATracts_halfAnd10']==1]['lasnaphalf'].isna().sum()

0

In [82]:
#It appears that all missing values for population/share of population variables are NaN if the census tract is not
#tagged as being a census tract with a flag for low access at 0.5 miles.
df_cook[df_cook['LATracts_half']==1]['lahisphalf'].isna().sum()

0

In [83]:
#The population living > 0.5 miles from a supermarket is not the same as the census tract population.
#There doesn't seem to be a clear way to impute what lapophalf or lapophalfshare would be in tracts that are not
#flagged as being low access at 0.5 miles. In effect, these variables are treated as being 0 in those census tracts. 
df_cook.iloc[100][['Pop2010','LATracts_half','lapophalf','lapophalfshare']]

Pop2010            2973
LATracts_half         1
lapophalf         559.0
lapophalfshare    18.82
Name: 21035, dtype: object

In [84]:
#Creating a dataframe replacing all NaN values by 0. This may not be the best approach- it may be better to drop 
#the columns with missing values.

#NaN_columns=[i for i in df_cook.columns if df_cook[i].isna().sum()!=0]
df_cook=df_cook.fillna(0)

In [85]:
df_cook.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1314 entries, 20935 to 22248
Data columns (total 63 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CensusTract           1314 non-null   int64
 1   State                 1314 non-null   object
 2   County                1314 non-null   object
 3   Urban                 1314 non-null   int64
 4   Pop2010               1314 non-null   int64
 5   OHU2010               1314 non-null   int64
 6   GroupQuartersFlag     1314 non-null   int64
 7   NUMGQTRS              1314 non-null   float64
 8   PCTGQTRS              1314 non-null   float64
 9   LILATracts_1And10     1314 non-null   int64
 10  LILATracts_halfAnd10  1314 non-null   int64
 11  LILATracts_1And20     1314 non-null   int64
 12  LILATracts_Vehicle    1314 non-null   int64
 13  HUNVFlag              1314 non-null   int64
 14  LowIncomeTracts       1314 non-null   int64
 15  PovertyRate           1314 non-null   float64
 16  MedianFamilyIncome    1314 non-null   float64
 17  LA1and10              1314 non-null   int64
 18  LAhalfand10           1314 non-null   int64
 19  LA1and20              1314 non-null   int64
 20  LATracts_half         1314 non-null   int64
 21  LATracts1             1314 non-null   int64
 22  LATracts10            1314 non-null   int64
 23  LATracts20            1314 non-null   int64
 24  LATractsVehicle_20    1314 non-null   int64
 25  lapophalf             1314 non-null   float64
 26  lapophalfshare        1314 non-null   float64
 27  lalowihalf            1314 non-null   float64
 28  lalowihalfshare       1314 non-null   float64
 29  lakidshalf            1314 non-null   float64
 30  lakidshalfshare       1314 non-null   float64
 31  laseniorshalf         1314 non-null   float64
 32  laseniorshalfshare    1314 non-null   float64
 33  lawhitehalf           1314 non-null   float64
 34  lawhitehalfshare      1314 non-null   float64
 35  lablackhalf           1314 non-null   float64
 36  lablackhalfshare      1314 non-null   float64
 37  laasianhalf           1314 non-null   float64
 38  laasianhalfshare      1314 non-null   float64
 39  lanhopihalf           1314 non-null   float64
 40  lanhopihalfshare      1314 non-null   float64
 41  laaianhalf            1314 non-null   float64
 42  laaianhalfshare       1314 non-null   float64
 43  laomultirhalf         1314 non-null   float64
 44  laomultirhalfshare    1314 non-null   float64
 45  lahisphalf            1314 non-null   float64
 46  lahisphalfshare       1314 non-null   float64
 47  lahunvhalf            1314 non-null   float64
 48  lahunvhalfshare       1314 non-null   float64
 49  lasnaphalf            1314 non-null   float64
 50  lasnaphalfshare       1314 non-null   float64
 51  TractLOWI             1314 non-null   float64
 52  TractKids             1314 non-null   float64
 53  TractSeniors          1314 non-null   float64
 54  TractWhite            1314 non-null   float64
 55  TractBlack            1314 non-null   float64
 56  TractAsian            1314 non-null   float64
 57  TractNHOPI            1314 non-null   float64
 58  TractAIAN             1314 non-null   float64
 59  TractOMultir          1314 non-null   float64
 60  TractHispanic         1314 non-null   float64
 61  TractHUNV             1314 non-null   float64
 62  TractSNAP             1314 non-null   float64
dtypes: float64(42), int64(19), object(2)
memory usage: 657.0+ KB

In [86]:
df_cook['lasnaphalf'].value_counts(dropna=False)

0.0      464
14.0      16
7.0       15
3.0       14
4.0       14
        ...
156.0      1
166.0      1
137.0      1
453.0      1
307.0      1
Name: lasnaphalf, Length: 317, dtype: int64

In [87]:
df_cook

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
20935,17031010100,Illinois,Cook County,1,4854,2302,0,218.0,4.49,0,...,277.0,1810.0,2437.0,150.0,1.0,33.0,423.0,616.0,1162.0,433.0
20936,17031010201,Illinois,Cook County,1,6450,2463,0,163.0,2.53,0,...,314.0,2312.0,2350.0,299.0,6.0,48.0,1435.0,2049.0,751.0,851.0
20937,17031010202,Illinois,Cook County,1,2818,1115,0,315.0,11.18,0,...,309.0,1237.0,953.0,143.0,1.0,18.0,466.0,789.0,464.0,232.0
20938,17031010300,Illinois,Cook County,1,6236,2826,0,791.0,12.68,0,...,884.0,3267.0,1722.0,346.0,16.0,21.0,864.0,1169.0,993.0,470.0
20939,17031010400,Illinois,Cook County,1,5042,2098,0,1349.0,26.76,0,...,263.0,3341.0,729.0,562.0,5.0,17.0,388.0,480.0,655.0,277.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22244,17031843500,Illinois,Cook County,1,11309,278,1,10273.0,90.84,0,...,228.0,3188.0,7603.0,21.0,1.0,22.0,474.0,2205.0,6.0,73.0
22245,17031843600,Illinois,Cook County,1,2807,1169,0,0.0,0.00,0,...,270.0,65.0,2653.0,10.0,0.0,3.0,76.0,47.0,449.0,479.0
22246,17031843700,Illinois,Cook County,1,2117,920,0,1.0,0.05,0,...,171.0,1656.0,106.0,88.0,1.0,19.0,247.0,516.0,143.0,77.0
22247,17031843800,Illinois,Cook County,1,2110,651,0,0.0,0.00,0,...,207.0,616.0,1119.0,110.0,0.0,23.0,242.0,380.0,182.0,199.0
22248,17031843900,Illinois,Cook County,1,3533,1935,0,26.0,0.74,1,...,563.0,129.0,3261.0,43.0,0.0,14.0,86.0,63.0,730.0,485.0

In [88]:
df_cook=df_cook.drop(["Urban","State","County"],axis=1)

In [89]:
df_cook.to_csv("FARA_Cook_County.csv")

In [90]:
test_df=pd.read_csv('FARA_Cook_County.csv')

In [91]:
test_df.head()

,Unnamed: 0,CensusTract,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,LILATracts_halfAnd10,LILATracts_1And20,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,20935,17031010100,4854,2302,0,218.0,4.49,0,1,0,...,277.0,1810.0,2437.0,150.0,1.0,33.0,423.0,616.0,1162.0,433.0
1,20936,17031010201,6450,2463,0,163.0,2.53,0,0,0,...,314.0,2312.0,2350.0,299.0,6.0,48.0,1435.0,2049.0,751.0,851.0
2,20937,17031010202,2818,1115,0,315.0,11.18,0,0,0,...,309.0,1237.0,953.0,143.0,1.0,18.0,466.0,789.0,464.0,232.0
3,20938,17031010300,6236,2826,0,791.0,12.68,0,1,0,...,884.0,3267.0,1722.0,346.0,16.0,21.0,864.0,1169.0,993.0,470.0
4,20939,17031010400,5042,2098,0,1349.0,26.76,0,0,0,...,263.0,3341.0,729.0,562.0,5.0,17.0,388.0,480.0,655.0,277.0